[project]
name = "spider-android"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "lamda>=7.75",
    "pyqt5>=5.15.11",
]
